const CONSTANT = {
    SUCCESS_CODE: 200,
    CREATED_CODE: 201,
    DELETED_CODE: 204,
    SERVER_ERROR_CODE: 500,
    BAD_REQUEST_CODE: 400,
    NOT_FOUND_CODE: 404,
    NOT_AUTHEN_CODE: 401,
    NOT_AUTHOR_CODE: 403,
    SUPER_ADMIN_ROLE_ID: 1,
    ADMIN_ROLE_ID: 2,
    SUB_ADMIN_ROLE_ID: 3,
};
export const FEATURE_PERMISSION = {
    CREATE_CUSTOMER: "CREATE_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    DETAIL_CUSTOMER: "DETAIL_CUSTOMER",
    SEARCH_CUSTOMER: "SEARCH_CUSTOMER",

    CREATE_MANIFEST: "CREATE_MANIFEST",
    UPDATE_MANIFEST: "UPDATE_MANIFEST",
    DELETE_MANIFEST: "DELETE_MANIFEST",
    DETAIL_MANIFEST: "DETAIL_MANIFEST",
    SEARCH_MANIFEST: "SEARCH_MANIFEST",

    CREATE_ADMIN: "CREATE_ADMIN",
    UPDATE_ADMIN: "UPDATE_ADMIN",
    DELETE_ADMIN: "DELETE_ADMIN",
    DETAIL_ADMIN: "DETAIL_ADMIN",
    SEARCH_ADMIN: "SEARCH_ADMIN",
};
Object.freeze(CONSTANT);
Object.freeze(FEATURE_PERMISSION);

export default CONSTANT;
