const CONSTANT = {
    SUCCESS_CODE: 200,
    CREATED_CODE: 201,
    DELETED_CODE: 204,
    SERVER_ERROR_CODE: 500,
    BAD_REQUEST_CODE: 400,
    NOT_FOUND_CODE: 404,
    NOT_AUTHEN_CODE: 401,
    NOT_AUTHOR_CODE: 403,
    SUPER_ADMIN_ROLE_ID : 1,
    ADMIN_ROLE_ID : 2,
    SUB_ADMIN_ROLE_ID : 3,
};
Object.freeze(CONSTANT);
export default CONSTANT;
