import { Button } from "antd";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useUser from "../hooks/useUser";
import { isEmpty } from "../utils/opLodash";

export default function Main() {
    const {user , clearUser} = useUser()
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main className={styles.main}>
                { isEmpty(user) ? <h1>Not login</h1> :  <h1>Login success : {user.name}</h1>}
                <br/>
                <br/>
                <br/>
                <Button type="primary " className="rounded-2xl" onClick={clearUser}>
                    Logout
                </Button>
                <div className="font-bold text-3xl">test tailwindcss class</div>
            </main>

        </div>
    );
}
